### ISSUE TITLE
Update SQL Queries to Handle NULL Values in is_entity_deleted Condition

### ISSUE THREAD

**Issue by rpallapolu** [ground-truth-ai/amlaidatatests#70]
From the generated SQL queries, we've identified that the condition is_entity_deleted IN (FALSE, NULL) only considers FALSE cases and disregards nulls(i.e., value can't be compared to NULL with an IN statement). To ensure both scenarios are accounted for, Can you update the generated queries condition to is_entity_deleted == FALSE OR is_entity_deleted IS NULL(where we have IN Statement with such cases)?. This change will prevent misleading counts or proportions in the SQL query outputs presented to customers.

https://github.com/ground-truth-ai/amlaidatatests/blob/c82dc91ac010b869d72f0c4c9d280c48329c467b/generated_sql/bigquery/DT017-CountMatchingRows-join_date_party.sql#L40

**Comment by ssabdb** [comment]
Yes, confirmed this is a bug. From the BQ documentation the IN list returns null and is documented as such:

```
When using the IN operator, the following semantics apply in this order:

Returns FALSE if value_set is empty.
Returns NULL if search_value is NULL.
Returns TRUE if value_set contains a value equal to search_value.
Returns NULL if value_set contains a NULL.
Returns FALSE.
```
